<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Doctor extends \Application\Entity\Doctor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Doctor' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Doctor' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\Doctor' . "\0" . 'specialization', '' . "\0" . 'Application\\Entity\\Doctor' . "\0" . 'timeSlots', '' . "\0" . 'Application\\Entity\\Doctor' . "\0" . 'appointments', '' . "\0" . 'Application\\Entity\\Doctor' . "\0" . 'createdAt', '' . "\0" . 'Application\\Entity\\Doctor' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Doctor' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Doctor' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\Doctor' . "\0" . 'specialization', '' . "\0" . 'Application\\Entity\\Doctor' . "\0" . 'timeSlots', '' . "\0" . 'Application\\Entity\\Doctor' . "\0" . 'appointments', '' . "\0" . 'Application\\Entity\\Doctor' . "\0" . 'createdAt', '' . "\0" . 'Application\\Entity\\Doctor' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Doctor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \Application\Entity\Doctor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecialization(): \Application\Entity\Specialization
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecialization', []);

        return parent::getSpecialization();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecialization(\Application\Entity\Specialization $specialization): \Application\Entity\Doctor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecialization', [$specialization]);

        return parent::setSpecialization($specialization);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeSlots(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeSlots', []);

        return parent::getTimeSlots();
    }

    /**
     * {@inheritDoc}
     */
    public function addTimeSlot(\Application\Entity\TimeSlot $timeSlot): \Application\Entity\Doctor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTimeSlot', [$timeSlot]);

        return parent::addTimeSlot($timeSlot);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTimeSlot(\Application\Entity\TimeSlot $timeSlot): \Application\Entity\Doctor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTimeSlot', [$timeSlot]);

        return parent::removeTimeSlot($timeSlot);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppointments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppointments', []);

        return parent::getAppointments();
    }

    /**
     * {@inheritDoc}
     */
    public function addAppointment(\Application\Entity\Appointment $appointment): \Application\Entity\Doctor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAppointment', [$appointment]);

        return parent::addAppointment($appointment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAppointment(\Application\Entity\Appointment $appointment): \Application\Entity\Doctor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAppointment', [$appointment]);

        return parent::removeAppointment($appointment);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize(): mixed
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
